#!/bin/sh -e

# /etc/perl/Net/libnet.cfg mistakenly installed as /etc/Net in perl 5.8
if [ "$1" = upgrade ] && [ -f /etc/Net ] && [ -x /usr/bin/md5sum ] &&
   [ "$(/usr/bin/md5sum /etc/Net)" = "fb2946cae573b8ed3d654a180d458733  /etc/Net" ]
then
    rm -f /etc/Net
fi

# this used to be a symlink, see #536384
if [ -h /usr/share/doc/perl-modules ]; then
    rm -f /usr/share/doc/perl-modules
fi

exit 0
